apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serviceaccount.yml
- view-rolebinding.yml
- serviceaccount-role.yml
- serviceaccount-rolebinding.yml
- deployment.yml
- service.yml
