apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: janus-mcp-server-role-binding
roleRef:
  kind: ClusterRole
  name: janus-mcp-server-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: janus-mcp-server
