apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/vcs-uri: https://github.com/hawtio/synapse.git
  labels:
    app.kubernetes.io/name: janus-mcp-server
  name: janus-mcp-server
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: janus-mcp-server
  type: ClusterIP