apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-terminal
  namespace: synapse
  labels:
    app: synapse
    deployment: synapse-terminal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse
      deployment: synapse-terminal
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: synapse
        deployment: synapse-terminal
    spec:
      containers:
        - name: synapse-terminal
          image: quay.io/hawtio/synapse-terminal
          imagePullPolicy: Always
          env:
          - name: SYNAPSE_APP_PORT
            value: 8080
          - name: LLM_PROVIDER
            valueFrom:
              secretKeyRef:
                name: synapse-terminal-llm-credentials
                key: provider
          - name: LLM_API_KEY
            valueFrom:
              secretKeyRef:
                name: synapse-terminal-llm-credentials
                key: key
          - name: LLM_NAME
            valueFrom:
              secretKeyRef:
                name: synapse-terminal-llm-credentials
                key: name
          - name: LLM_BASE_URL
            valueFrom:
              secretKeyRef:
                name: synapse-terminal-llm-credentials
                key: url
          ports:
          - name: express
            containerPort: 8080
          livenessProbe:
            httpGet:
              path: /status
              port: express
              scheme: HTTP
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /status
              port: express
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
          resources:
            requests:
              memory: 32Mi
            limits:
              memory: 500Mi
